### PR TITLE
New Sound Effects

### PR DESCRIPTION
**Pull request by red-kangaroo**
Add some new sound effects. All should be CC Attribution to FreeSoundEffects.com, so added them to Credits.

This PR should be possible to merge on its own, but some of the sounds are based on  changes introduced in #576

### CODE REVIEW

File: Main/Source/gods.cpp [hunk 1]
```diff
@@ -1349,6 +1349,26 @@ void infuscor::PrayGoodEffect()
...
+  {
+    beamdata Beam
+      (
+        0,
+        CONST_S("drowned by the blood of ") + GetName(),
+        YOURSELF,
+        0
+      );
+    lsquare* Square = PLAYER->GetLSquareUnder();
+    Square->LiquidRain(Beam, BLOOD);
```
Comment (fejoa) [inline Main/Source/gods.cpp]: Got a build error here:

```
[ 72%] Building CXX object Main/CMakeFiles/ivan.dir/Source/godset.cpp.o

In file included from /home/travis/build/Attnam/ivan/Main/Source/godset.cpp:40:

/home/travis/build/Attnam/ivan/Main/Source/gods.cpp:1363:13: error: no member

      named 'LiquidRain' in 'lsquare'

    Square->LiquidRain(Beam, BLOOD);

    ~~~~~~  ^

1 error generated.

make[2]: *** [Main/CMakeFiles/ivan.dir/Source/godset.cpp.o] Error 1

make[1]: *** [Main/CMakeFiles/ivan.dir/all] Error 2

make: *** [all] Error 2

The command "make" exited with 2.
```

Comment (red-kangaroo) [reply Main/Source/gods.cpp]: Oops, I forgot I added LiquidRain in the Aslona branch. I'll update this with current master, then it should be OK.

Comment (fejoa) [reply Main/Source/gods.cpp]: It's fixed by #576
