### ISSUE TITLE
Issue Compiling - error: ‘Abort’ is not a member of ‘globalerrorhandler’

### ISSUE THREAD

**Issue by Tuerai** [Attnam/ivan#233]
Full text from the console during my compilation attempt is here:
https://hastebin.com/raw/etixiwotop
Downloaded source with "git clone", then followed instructions to build. 
Using gcc/g++ 4.7.2 and cmake version 2.8.12.2

**Comment by emlai** [comment]
GCC 4.7 doesn't seem to support C++11 attributes. In this case the error is caused by [`[[noreturn]]`](https://github.com/Attnam/ivan/blob/b5906ecfcbfda67e01074c875d1b751b71cfda18/FeLib/Include/error.h#L29).

Try upgrading your GCC to a newer version. 4.8 and later seem to have full C++11 support.

**Comment by Tuerai** [comment]
Upgraded gcc to 4.8 and then had to upgrade libsdl2 also, but got it working, thanks!

**Comment by emlai** [comment]
Great!

By the way it should also work with SDL 1.2. If it doesn't, that's a bug. Some early SDL 2.0 versions have some bugs though that affect the game.
