### ISSUE TITLE
Multiple problems related to sound support

### ISSUE THREAD

**Issue by AMDmi3** [Attnam/ivan#644]
After update to 0.59 on FreeBSD:
- it no longer builds with `-DNOSOUND` (which I've used for 0.58):
```
/wrkdirs/usr/ports/games/ivan/work/ivan-059/Main/Source/iconf.cpp:1189:3: error: use of undeclared identifier 'soundeffects'
  soundeffects::SetSfxVolume(SfxVolume.Value);
  ^
```
- it builds fine without NOSOUND, but there's an error message when starting a game
![sound](https://user-images.githubusercontent.com/474217/147354693-460b829c-b800-4ca7-a291-4985ff012202.png)

(which is also not removed cleanly and the game then paints over it).

With that, the game is playable, but there's no sound. I expect MIDI not to work on FreeBSD as it seem to be dependent on ALSA, but SDL_mixer should work fine.

**Comment by AquariusPower** [comment]
strange, I downloaded the 30MB src code of the tag v059 and: `egrep "fragment" -irnI`  
but there is no fragment error message on the code.
I guess it may be coming from something external to ivan.

To enable midi you need some synth working:
https://github.com/Attnam/ivan/issues/637#issuecomment-1007860961
